TestCrowd/Areas/Testing/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestCrowd.DataAccess.Model;
using TestCrowd.DataAccess.Repository;

namespace TestCrowd.Areas.Testing.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        // GET: Testing/Profile
        [Authorize(Roles = "company, tester, admin")]
        public ActionResult Index()
        {
            if (User.IsInRole("company"))
            {
                var company = new ApplicationUserRepository<Company>().GetByUserName(User.Identity.Name);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("CompanyProfile", company);
                }

                return View("CompanyProfile", company);
            }

            if (User.IsInRole("admin"))
            {
                var admin = new ApplicationUserRepository<Admin>().GetByUserName(User.Identity.Name);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("AdminProfile", admin);
                }

                return View("AdminProfile", admin);
            }

            var tester = new ApplicationUserRepository<Tester>().GetByUserName(User.Identity.Name);

            if (Request.IsAjaxRequest())
            {
                return PartialView("TesterProfile", tester);
            }

            return View("TesterProfile", tester);
        }
    }
}

TestCrowd/Areas/Testing/Controllers/TestsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DataTables.AspNet.Core;
using DataTables.AspNet.Mvc5;
using TestCrowd.DataAccess.Model;
using TestCrowd.DataAccess.Model.Evidences;
using TestCrowd.DataAccess.Model.Reviews;
using TestCrowd.DataAccess.Model.Tests;
using TestCrowd.DataAccess.Repository;
using TestCrowd.DataAccess.Repository.Evidences;
using TestCrowd.DataAccess.Repository.Reviews;
using TestCrowd.DataAccess.Repository.Tests;

namespace TestCrowd.Areas.Testing.Controllers
{
    [Authorize(Roles = "company, tester")]
    public class TestsController : Controller
    {
        // GET: Testing/Tests
        public ActionResult Index()
        {
            if (User.IsInRole("company"))
            {
                return RedirectToAction("CompanyTests");
            }

            return RedirectToAction("TesterTests");
        }

        [Authorize(Roles = "company")]
        public ActionResult CompanyTests()
        {
            return View();
        }

        [Authorize(Roles = "company")]
        public ActionResult TestsResaults(int? page, Guid? testCaseGuid, Guid? statusGuid)
        {
            TestsRepository testsRepo = new TestsRepository();

            ApplicationUserRepository<Company> userRepo = new ApplicationUserRepository<Company>();
            Company company = userRepo.GetByUserName(User.Identity.Name);

            TestCaseRepository testCaseRepo = new TestCaseRepository();
            ViewBag.TestCases = testCaseRepo.GetAllForCompany(company);

            TestStatusRepository statusRepo = new TestStatusRepository();
            ViewBag.Statuses = statusRepo.GetAll();

            int itemsOnPage = 20;
            int pg = page ?? 1;
            int startIndex = (pg * itemsOnPage) - itemsOnPage;

            TestCase testCase = null;
            if (testCaseGuid != null)
            {
                testCase = testCaseRepo.GetById((Guid)testCaseGuid);
                ViewBag.TestCase = testCase;
            }

            TestStatus testStatus = null;
            if (statusGuid != null)
            {
                testStatus = statusRepo.GetById((Guid)statusGuid);
                ViewBag.Status = testStatus;
            }

            IList<DataAccess.Model.Tests.Tests> testses = testsRepo.GetTestsForCompany(company, out int totalTests, out int filteredCount, testCase, testStatus, startIndex, itemsOnPage);

            ViewBag.Pages = (int)Math.Ceiling((double)totalTests / (double)itemsOnPage);
            ViewBag.CurrentPage = pg;

            if (Request.IsAjaxRequest())
            {
                return PartialView(testses);
            }

            return View(testses);
        }

        [HttpPost]
        [Authorize(Roles = "company")]
        public ActionResult CompanyTestsDataTable(IDataTablesRequest request)
        {
            ApplicationUserRepository<Company> companyRepo = new ApplicationUserRepository<Company>();
            var company = companyRepo.GetByUserName(User.Identity.Name);
            var testCaseRepo = new TestCaseRepository();

            var orderColumn = request.Columns.Where(c => c.Sort != null).First();

            bool asc;
            if (orderColumn.Sort.Direction == 0)
            {
                asc = true;
            }
            else
            {
                asc = false;
            }

            var testCases = testCaseRepo.GetEntitiesForCompany(out int totalCount, out int filteredCount, request.Start, request.Length, nameof(TestCase.Name), request.Search.Value, orderColumn.Name, asc, company).Select(x => new
            {
                x.Id,
                x.Name,
                x.SkillDificulty,
                x.TimeDificulty,
                x.Reward,
                x.Rating,
                x.Created,
                x.AvailableTo,
                x.SoftwareType,
                x.Category
            });

            var response = DataTablesResponse.Create(request, totalCount, filteredCount, testCases);

            return new DataTablesJsonResult(response, JsonRequestBehavior.DenyGet);
        }

        [Authorize(Roles = "company")]
        public ActionResult CreateTestCase()
        {
            SoftwareTypeRepository swTypeRepo = new SoftwareTypeRepository();
            IList<SoftwareType> swTypes = swTypeRepo.GetAllValid();
            ViewBag.SoftwareTypes = swTypes;

            TestCategoryRepository testCatRepo = new TestCategoryRepository();
            IList<TestCategory> testCats = testCatRepo.GetAllValid();
            ViewBag.TestCategories = testCats;

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "company")]
        public async Task<ActionResult> AddTest(TestCase testCase, HttpPostedFileBase[] files)
        {
            ModelState.Remove(nameof(testCase.Evidences));
            ModelState.Remove(nameof(testCase.Rating));
            ModelState.Remove(nameof(testCase.Created));
            ModelState.Remove(nameof(testCase.Creator));
            ModelState.Remove(nameof(testCase.Reviews));
            ModelState.Remove(nameof(testCase.IsInGroup));
            ModelState.Remove("SoftwareType.Name");
            ModelState.Remove("Category.Name");
            ModelState.Remove("files");
            if (ModelState.IsValid)
            {
                TestCategoryRepository testCatRepo = new TestCategoryRepository();
                SoftwareTypeRepository swTypeRepo = new SoftwareTypeRepository();
                ApplicationUserRepository<Company> userRepo = new ApplicationUserRepository<Company>();
                IList<Evidence> evidences = new List<Evidence>();

                if (testCase.AvailableTo <= DateTime.Now)
                {
                    IList<SoftwareType> swTypes = swTypeRepo.GetAllValid();
                    IList<TestCategory> testCats = testCatRepo.GetAllValid();
                    ViewBag.SoftwareTypes = swTypes;
                    ViewBag.TestCategories = testCats;

                    TempData["error"] = "Available To must be in future!";
                    return View("CreateTestCase", testCase);
                }

                if (files[0] != null)
                {
                    var maxSizeInMb = 20;
                    var byteSize = 1048576;
                    var maxSizeInBytes = byteSize * maxSizeInMb;
                    foreach (var file in files)
                    {
                        if (file.ContentLength > maxSizeInBytes)
                        {
                            IList<SoftwareType> swTypes = swTypeRepo.GetAllValid();
                            IList<TestCategory> testCats = testCatRepo.GetAllValid();
                            ViewBag.SoftwareTypes = swTypes;
                            ViewBag.TestCategories = testCats;

                            TempData["error"] = "File " + file.FileName + " is too big! (max size is " + maxSizeInMb + "MB)";
                            return View("CreateTestCase", testCase);
                        }
                    }

                    foreach (var file in files)
                    {
                        Evidence evidence = new Evidence();
                        evidence.Id = Guid.NewGuid();
                        evidence.Name = evidence.Id.ToString();
                        evidence.RealName = Path.GetFileNameWithoutExtension(file.FileName);
                        evidence.Attached = DateTime.Now;

                        var extension = Path.GetExtension(file.FileName);
                        evidence.Extension = extension;

                        var path = Path.Combine(Server.MapPath("~/Uploads"), evidence.Name + extension);
                        Directory.CreateDirectory(Server.MapPath("~/Uploads"));
                        file.SaveAs(path);

                        evidences.Add(evidence);
                    }

                    testCase.Evidences = evidences;
                }

                var swType = swTypeRepo.GetByIdAsync(testCase.SoftwareType.Id);
                var testCat = testCatRepo.GetByIdAsync(testCase.Category.Id);
                var currentUser = userRepo.GetByUserNameAsync(User.Identity.Name);

                testCase.SoftwareType = await swType;
                testCase.Category = await testCat;
                testCase.Creator = await currentUser;
                testCase.Created = DateTime.Now;

                TestCaseRepository testRepo = new TestCaseRepository();
                EvidenceRepository evidRepo = new EvidenceRepository();

                foreach (var evidence in evidences)
                {
                    evidRepo.Create(evidence);
                }
                testRepo.Create(testCase);
                TempData["success"] = "Test case was added";
            }
            else
            {
                SoftwareTypeRepository swTypeRepo = new SoftwareTypeRepository();
                IList<SoftwareType> swTypes = swTypeRepo.GetAllValid();
                ViewBag.SoftwareTypes = swTypes;

                TestCategoryRepository testCatRepo = new TestCategoryRepository();
                IList<TestCategory> testCats = testCatRepo.GetAllValid();
                ViewBag.TestCategories = testCats;

                if (!swTypeRepo.IsSwTypeExist(testCase.SoftwareType.Id))
                {
                    TempData["error"] = "Please select Software type!";
                    return View("CreateTestCase", testCase);
                }

                if (!testCatRepo.IsTestCatExist(testCase.Category.Id))
                {
                    TempData["error"] = "Please select Category!";
                    return View("CreateTestCase", testCase);
                }

                return View("CreateTestCase", testCase);
            }

            return RedirectToAction("CompanyTests");
        }

TestCrowd/Areas/Testing/Views/Home/MenuPartials/MenuAdmin.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
        <div class="sidebar-brand-icon">
            <img src="@Url.Content("~/NewBiz/img/logo-white.png")" class="toggleLogo">
        </div>
        <div class="sidebar-brand-text mx-3">
            <img src="@Url.Content("~/NewBiz/img/logo-text-white.png")" alt="TestCrowdLogo" class="toggleTextLogo">
        </div>
        <!---->
    </a>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <!-- Divider -->
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Profile
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Profile")">
            <i class="fas fa-fw fa-user"></i>
            <span>Info</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Administration
    </div>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Admins", "Administration")">
            <i class="fas fa-fw fa-user-cog"></i>
            <span>Admins</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("SoftwareTypes", "Administration")">
            <i class="fas fa-fw fa-atlas"></i>
            <span>Software types</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("TestCategories", "Administration")">
            <i class="fas fa-fw fa-sitemap"></i>
            <span>Test categories</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

TestCrowd/Areas/Testing/Views/Home/MenuPartials/MenuCompany.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
        <div class="sidebar-brand-icon">
            <img src="@Url.Content("~/NewBiz/img/logo-white.png")" class="toggleLogo">
        </div>
        <div class="sidebar-brand-text mx-3">
            <img src="@Url.Content("~/NewBiz/img/logo-text-white.png")" alt="TestCrowdLogo" class="toggleTextLogo">
        </div>
        <!---->
    </a>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-bug"></i>
            <span>Tests</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Tests:</h6>
                <a class="collapse-item" href="@Url.Action("CompanyTests", "Tests")">Our Tests</a>
                <a class="collapse-item" href="@Url.Action("TestsResaults", "Tests")">Test results</a>
                <h6 class="collapse-header">Test Groups:</h6>
                <a class="collapse-item" href="@Url.Action("CompanyTestGroups", "TestGroups")">Our Test groups</a>
            </div>
        </div>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Profile
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Profile")">
            <i class="fas fa-fw fa-user"></i>
            <span>Info</span>
        </a>
    </li>
    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Deposit", "Payment")">
            <i class="fas fa-fw fa-hand-holding-usd"></i>
            <span>Deposit credits</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

TestCrowd/Areas/Testing/Views/Home/MenuPartials/MenuTester.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
        <div class="sidebar-brand-icon">
            <img src="@Url.Content("~/NewBiz/img/logo-white.png")" class="toggleLogo">
        </div>
        <div class="sidebar-brand-text mx-3">
            <img src="@Url.Content("~/NewBiz/img/logo-text-white.png")" alt="TestCrowdLogo" class="toggleTextLogo">
        </div>
        <!---->
    </a>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-bug"></i>
            <span>Tests</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Tests:</h6>
                <a class="collapse-item" href="@Url.Action("TesterTests", "Tests")">Catalog</a>
                <a class="collapse-item" href="@Url.Action("TakenedTests", "Tests")">Takened</a>
                <a class="collapse-item" href="@Url.Action("FinishedTests", "Tests")">Finished</a>
                <h6 class="collapse-header">Test Groups:</h6>
                <a class="collapse-item" href="@Url.Action("TesterTestGroups", "TestGroups")">Catalog</a>
                <a class="collapse-item" href="@Url.Action("TakenedTestGroups", "TestGroups")">Takened</a>
                <a class="collapse-item" href="@Url.Action("FinishedTestGroups", "TestGroups")">Finished</a>
            </div>
        </div>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Profile
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Profile")">
            <i class="fas fa-fw fa-user"></i>
            <span>Info</span>
        </a>
    </li>
    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Withdraw", "Payment")">
            <i class="fas fa-fw fa-hand-holding-usd"></i>
            <span>Withdraw credits</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->