TestCrowd/Areas/Testing/Controllers/TestGroupsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CsQuery.ExtensionMethods;
using CsQuery.ExtensionMethods.Internal;
using DataTables.AspNet.Core;
using DataTables.AspNet.Mvc5;
using TestCrowd.DataAccess.Model;
using TestCrowd.DataAccess.Model.Evidences;
using TestCrowd.DataAccess.Model.Tests;
using TestCrowd.DataAccess.Repository;
using TestCrowd.DataAccess.Repository.Evidences;
using TestCrowd.DataAccess.Repository.Reviews;
using TestCrowd.DataAccess.Repository.Tests;

namespace TestCrowd.Areas.Testing.Controllers
{
    [Authorize(Roles = "company, tester")]
    public class TestGroupsController : Controller
    {
        // GET: Testing/TestGroups
        public ActionResult Index()
        {
            if (User.IsInRole("company"))
            {
                return RedirectToAction("CompanyTestGroups");
            }

            return RedirectToAction("TesterTestGroups");
        }

        [Authorize(Roles = "company")]
        public ActionResult CompanyTestGroups()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "company")]
        public ActionResult CompanyTestGroupsDataTable(IDataTablesRequest request)
        {
            ApplicationUserRepository<Company> companyRepo = new ApplicationUserRepository<Company>();
            var company = companyRepo.GetByUserName(User.Identity.Name);
            var testGroupRepo = new TestGroupRepository();

            var orderColumn = request.Columns.Where(c => c.Sort != null).First();

            bool asc;
            if (orderColumn.Sort.Direction == 0)
            {
                asc = true;
            }
            else
            {
                asc = false;
            }

            var testGroups = testGroupRepo.GetEntitiesForCompany(out int totalCount, out int filteredCount, request.Start, request.Length, nameof(TestCase.Name), request.Search.Value, orderColumn.Name, asc, company);

            var resault = testGroups.Select(x => new
            {
                x.Id,
                x.Name,
                x.SkillDificulty,
                x.TimeDificulty,
                x.RewardMultiplier,
                x.Rating,
                x.Created,
                x.AvailableTo,
                testCasesCount = x.TestCases.Count
            });

            var response = DataTablesResponse.Create(request, totalCount, filteredCount, resault);

            return new DataTablesJsonResult(response, JsonRequestBehavior.DenyGet);
        }

        [Authorize(Roles = "company")]
        public ActionResult CreateTestGroup()
        {
            return View();
        }

        public JsonResult GetTestCases(string searchTerm)
        {
            ApplicationUserRepository<Company> companyRepo = new ApplicationUserRepository<Company>();
            Company currentCompany = companyRepo.GetByUserName(User.Identity.Name);

            TestCaseRepository testCaseRepo = new TestCaseRepository();

            IList<TestCase> testCases;
            testCases = !string.IsNullOrEmpty(searchTerm) ? testCaseRepo.GetFilteredForCompanyNotInGroup(currentCompany, nameof(TestCase.Name), searchTerm) : testCaseRepo.GetFilteredForCompanyNotInGroup(currentCompany);

            var modifiedData = testCases.Select(x => new
            {
                id = x.Id,
                text = x.Name + " (available to: " + x.AvailableTo.ToShortDateString() + ")"
            });
            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize(Roles = "company")]
        public ActionResult AddTestGroup(TestGroup testGroup, string data)
        {
            if (string.IsNullOrEmpty(data))
            {
                TempData["error"] = "At least one test case must be selected!";
                return View("CreateTestGroup");
            }

            ModelState.Remove(nameof(TestGroup.TestCases));
            ModelState.Remove(nameof(TestGroup.Created));
            ModelState.Remove(nameof(TestGroup.Creator));
            ModelState.Remove(nameof(TestGroup.Rating));
            ModelState.Remove(nameof(TestGroup.TimeDificulty));
            ModelState.Remove(nameof(TestGroup.SkillDificulty));
            if (ModelState.IsValid)
            {
                ApplicationUserRepository<Company> userRepo = new ApplicationUserRepository<Company>();
                Company currentUser = userRepo.GetByUserName(User.Identity.Name);

                var testCasesId = data.Split(',');
                TestCaseRepository testCaseRepo = new TestCaseRepository();
                IList<TestCase> testCases = new List<TestCase>();

                foreach (var testCaseId in testCasesId)
                {
                    TestCase tempTestCase = testCaseRepo.GetByIdForCompanyNotInGroup(currentUser, Guid.Parse(testCaseId));
                    tempTestCase.IsInGroup = true;
                    testCases.Add(tempTestCase);
                }

                DateTime latestAvailability = testCases.OrderByDescending(x => x.AvailableTo).First().AvailableTo;
                if (testGroup.AvailableTo < latestAvailability)
                {
                    TempData["error"] = $"Available To must be equal or greater than availability of latest test case ({latestAvailability.ToShortDateString()})!";
                    return View("CreateTestGroup");
                }

                testGroup.TestCases = testCases;
                testGroup.SkillDificulty = testGroup.CountSkillDificulty();
                testGroup.TimeDificulty = testGroup.CountTimeDificulty();

                testGroup.RewardMultiplier = (testGroup.RewardMultiplier + 100) / 100;

                testGroup.Creator = currentUser;
                testGroup.Created = DateTime.Now;

                foreach (var testCase in testCases)
                {
                    testCaseRepo.Update(testCase);
                }

                TestGroupRepository testGroupRepo = new TestGroupRepository();
                testGroupRepo.Create(testGroup);

                TempData["success"] = "Test group was added";
            }
            else
            {
                return View("CreateTestGroup");
            }

            return RedirectToAction("CompanyTestGroups");
        }

        [Authorize(Roles = "company")]
        public ActionResult DetailTestGroupCompany(string id)
        {
            var testGroupRepo = new TestGroupRepository();
            var testGroup = testGroupRepo.GetById(Guid.Parse(id));

            return View(testGroup);
        }

        [Authorize(Roles = "company")]
        public ActionResult DeleteTestGroup(IList<TestGroup> rows)
        {        
            foreach (var row in rows)
            {
                var testGroupRepo = new TestGroupRepository();
                TestGroup testGroup = testGroupRepo.GetById(row.Id);
                foreach (var testCase in testGroup.TestCases)
                {
                    testCase.IsInGroup = false;
                }

                testGroupRepo.Update(testGroup);
                testGroupRepo.Delete(testGroup);
            }

            TempData["success"] = "Test group/s was deleted!";

            return View("CompanyTestGroups");
        }

        [Authorize(Roles = "company")]
        public ActionResult DeleteTestGroupAll(IList<TestGroup> rows)
        {
            IList<Guid> testCasesId = new List<Guid>();
            foreach (var row in rows)
            {
                var testGroupRepo = new TestGroupRepository();
                TestGroup testGroup = testGroupRepo.GetById(row.Id);
                foreach (var testCase in testGroup.TestCases)
                {
                    testCase.IsInGroup = false;
                    testCasesId.Add(testCase.Id);
                }

                testGroupRepo.Update(testGroup);
                testGroupRepo.Delete(testGroup);
            }

            TestCaseRepository testCaseRepo = new TestCaseRepository();
            foreach (var id in testCasesId)
            {
                TestCase testCase = testCaseRepo.GetById(id);

                if (testCase.Evidences != null && testCase.Evidences.Count > 0)
                {
                    var evidenceRepo = new EvidenceRepository();
                    foreach (var evidence in testCase.Evidences)
                    {
                        System.IO.File.Delete(Server.MapPath("~/Uploads/" + evidence.Name + evidence.Extension));
                        evidenceRepo.Delete(evidence);
                    }
                }

                if (testCase.Reviews != null && testCase.Reviews.Count > 0)
                {
                    var reviewsRepo = new ReviewRepository();
                    foreach (var review in testCase.Reviews)
                    {
                        reviewsRepo.Delete(review);
                    }
                }

                testCaseRepo.Delete(testCase);
            }

            TempData["success"] = "Test group/s and tests was deleted!";

            return View("CompanyTestGroups");
        }

        [Authorize(Roles = "company")]
        public ActionResult EditTestGroup(string id)
        {
            var testGroupRepo = new TestGroupRepository();
            var testGroup = testGroupRepo.GetById(Guid.Parse(id));

            return View(testGroup);
        }

        [Authorize(Roles = "company")]
        public ActionResult DeleteAttachedTestCase(string id, string testCaseId)
        {
            TestGroupRepository testGroupRepo = new TestGroupRepository();
            TestCaseRepository testCaseRepo = new TestCaseRepository();

            TestGroup testGroup = testGroupRepo.GetById(Guid.Parse(id));
            if (testGroup.TestCases != null && testGroup.TestCases.Count > 0)
            {
                foreach (var tempTestCase in testGroup.TestCases)

TestCrowd/Areas/Testing/Views/TestGroups/CreateTestGroup.cshtml
@using TestCrowd.DataAccess.Model.Tests
@model TestCrowd.DataAccess.Model.Tests.TestGroup
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Testing/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/css/select2.css")" rel="stylesheet" />

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Test group - @ViewBag.Title</h1>

    <div class="card shadow mb-4">
        <div class="card-body">
            @if (TempData["error"] != null)
            {
                <br />
                <div class=" alert card border-left-danger shadow h-50 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Error</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@TempData["error"]</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-exclamation-circle fa-2x text-danger"></i>
                            </div>
                        </div>
                    </div>
                </div>
            }
            @using (Html.BeginForm("AddTestGroup", "TestGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group row">
                    <div class="col-sm-3">
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control form-control-user", @placeholder = "Test group name" })
                        <p class="small">@Html.ValidationMessageFor(x => x.Name)</p>
                    </div>
                </div>

                <div class="form-group row col-sm-6">
                    <p class=" align-content-center">Available to:</p>
                    <div class="form-group col-sm-4">
                        @Html.TextBoxFor(x => x.AvailableTo, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
                        <p class="small">@Html.ValidationMessageFor(x => x.AvailableTo)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-3 mb-3 mb-sm-0">
                        <p class="align-content-center mb-0">Test cases:</p>
                        <p class="align-content-center text-xs">(Available To must be equal or greater than availability of latest test case!)</p>
                        <input type="hidden" id="testCasesVal" name="data"/>
                        <select class="mySelect2 form-control form-control-user"></select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2 mb-3 mb-sm-0">
                        <p class="align-content-center mb-0">Reward multiplier:</p>
                        <p class="align-content-center text-xs">(applied to each test case)</p>
                        <div class="input-group">
                            @Html.TextBoxFor(x => x.RewardMultiplier, new { @class = "form-control form-control-user", @placeholder = "Enter value (0-100)", @type = "number", @min = "0", @max = "100", @step = "1", @id = "myPercent" })
                            <div class="input-group-append">
                                <div class="btn bg-primary text-white">
                                    <i class="fas fa-percentage"></i>
                                </div>
                            </div>
                        </div>
                        <p class="small">@Html.ValidationMessageFor(x => x.RewardMultiplier)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2 mb-3 mb-sm-0">
                        <a href="@Url.Action("CompanyTestGroups")" class="btn btn-primary btn-user btn-block">Back</a>
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-user btn-block">Create test group</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/select2.min.js")"></script>

<script>
    $(document).ready(function () {
        $('#myPercent').keypress(function (field) {
            field.preventDefault();
        });

        $(".mySelect2").select2({
            placeholder: "Select test cases",
            allowClear: true,
            multiple: true,
            ajax: {
                url: "@Url.Action("GetTestCases", "TestGroups")",
                datatype: 'json',
                delay: 250,
                multiple: true,
                data: function(params) {
                    return {
                        searchTerm: params.term
                    };
                },
                processResults: function(data, params) {
                    return {
                        results: data
                    };
                }
            }
        });

        $(".mySelect2").on("change",
            function() {
                var testCaseId = $(this).val();
                $("#testCasesVal").val(testCaseId);
            });
    });

</script>

TestCrowd/Areas/Testing/Views/TestGroups/DetailTestGroupCompany.cshtml
@using TestCrowd.DataAccess.Model.Tests
@model TestCrowd.DataAccess.Model.Tests.TestGroup
@{
                /**/

                ViewBag.Title = "Detail";
                Layout = "~/Areas/Testing/Views/Shared/_Layout.cshtml";
}

<script src="https://cloud.tinymce.com/5/tinymce.min.js"></script>
<script>tinymce.init({ selector: 'textarea' });</script>

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">TestGroup - @Model.Name</h1>

    <div class="card shadow mb-4">
        <div class="card-body">
                <div class="form-group row col-sm-6">
                    <p class=" align-content-center">Skill difficulty:</p>
                    <div class="ratingDetail">
                        @Html.RadioButtonFor(x => x.SkillDificulty, 5, new { @id = "skillstar5", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("5 stars", new { @title = "text", @for = "skillstar5" })
                        @Html.RadioButtonFor(x => x.SkillDificulty, 4, new { @id = "skillstar4", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("4 stars", new { @title = "text", @for = "skillstar4" })
                        @Html.RadioButtonFor(x => x.SkillDificulty, 3, new { @id = "skillstar3", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("3 stars", new { @title = "text", @for = "skillstar3" })
                        @Html.RadioButtonFor(x => x.SkillDificulty, 2, new { @id = "skillstar2", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("2 stars", new { @title = "text", @for = "skillstar2" })
                        @Html.RadioButtonFor(x => x.SkillDificulty, 1, new { @id = "skillstar1", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("1 stars", new { @title = "text", @for = "skillstar1" })
                    </div>
                </div>

                <div class="form-group row col-sm-6">
                    <p class=" align-content-center">Time difficulty:</p>
                    <div class="ratingDetail">
                        @Html.Label("5 stars", new { @title = "text", @for = "timestar5" })
                        @Html.RadioButtonFor(x => x.TimeDificulty, 4, new { @id = "timestar4", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("4 stars", new { @title = "text", @for = "timestar4" })
                        @Html.RadioButtonFor(x => x.TimeDificulty, 3, new { @id = "timestar3", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("3 stars", new { @title = "text", @for = "timestar3" })
                        @Html.RadioButtonFor(x => x.TimeDificulty, 2, new { @id = "timestar2", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("2 stars", new { @title = "text", @for = "timestar2" })
                        @Html.RadioButtonFor(x => x.TimeDificulty, 1, new { @id = "timestar1", @name = "ratingDetail", @disabled = "true" })
                        @Html.Label("1 stars", new { @title = "text", @for = "timestar1" })
                    </div>
                </div>

            <div class="form-group row col-sm-6">
                <p class=" align-content-center">Avilable to:</p>
                <div class="form-group col-sm-4">
                    @Html.TextBoxFor(x => x.AvailableTo, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control", @readonly = "true" })
                </div>
            </div>
            <div class="form-group row col-sm-6">
                <p class=" align-content-center">Reward multiplier:</p>
                <div class="form-group col-sm-4">
                    <div class="input-group">
                        <input type="number" value="@Html.Raw((int)(Model.RewardMultiplier*100)-100)" readonly="true" class="form-control form-control-user" />
                        <div class="input-group-append">
                            <div class="btn bg-primary text-white">
                                <i class="fas fa-percentage"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="form-group row">
                    <div class="col-auto mb-3 mb-sm-0">
                        @if (Model.TestCases != null && Model.TestCases.Count > 0)
                        {
                            <p class=" align-content-center">Test cases:</p>
                            <table>
                                <tbody>
                                    @foreach (var testCase in Model.TestCases)
                                    {
                                    <tr class="border-left-primary border" id="detailTr">
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" width="500" class="text-left">@testCase.Name</td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" width="250" class="text-center">
                                            Skill dificulty:
                                            @{
                                                for (var i = 0; i < testCase.SkillDificulty; i++)
                                                {
                                                    <span class="icon text-primary"><i class="fas fa-star"></i></span>
                                                }
                                                for (var i = 0; i < 5 - testCase.SkillDificulty; i++)
                                                {
                                                    <span class="icon text-primary"><i class="far fa-star"></i></span>
                                                }
                                            }
                                        </td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" width="250" class="text-center">
                                            Time dificulty:
                                            @{
                                                for (var i = 0; i < testCase.TimeDificulty; i++)
                                                {
                                                    <span class="icon text-primary"><i class="fas fa-star"></i></span>
                                                }
                                                for (var i = 0; i < 5 - testCase.TimeDificulty; i++)
                                                {
                                                    <span class="icon text-primary"><i class="far fa-star"></i></span>
                                                }
                                            }
                                        </td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" width="200" class="text-center">Available to: @testCase.AvailableTo.ToShortDateString()</td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" class="text-center">
                                            <a href="@Url.Action("DetailTestCaseCompany", "Tests", new {id = testCase.Id})" class="btn btn-primary btn-user btn-block">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-share-square"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                </div>                
                <div class="form-group row">
                    <div class="col-sm-2 mb-3 mb-sm-0">
                        @if(Request.UrlReferrer != null)
                        {
                            <a class="btn btn-primary btn-user btn-block" onclick="history.go(-1); return false;" href="#">Back</a><br />
                        }
                        else
                        {
                            <a href="@Url.Action("CompanyTestGroups")" class="btn btn-primary btn-user btn-block">Back</a>
                        }

                    </div>
                </div>
        </div>
    </div>
</div>

TestCrowd/Areas/Testing/Views/TestGroups/EditTestGroup.cshtml
@using TestCrowd.DataAccess.Model.Tests
@model TestCrowd.DataAccess.Model.Tests.TestGroup
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Testing/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/css/select2.css")" rel="stylesheet" />

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Test group - @ViewBag.Title</h1>

    <div class="card shadow mb-4">
        <div class="card-body">
            @if (TempData["error"] != null)
            {
                <br />
                <div class=" alert card border-left-danger shadow h-50 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Error</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@TempData["error"]</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-exclamation-circle fa-2x text-danger"></i>
                            </div>
                        </div>
                    </div>
                </div>
            }
            @using (Html.BeginForm("UpdateTestGroup", "TestGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(x => x.Id)

                <div class="form-group row">
                    <div class="col-sm-3">
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control form-control-user", @placeholder = "Test group name" })
                        <p class="small">@Html.ValidationMessageFor(x => x.Name)</p>
                    </div>
                </div>

                <div class="form-group row col-sm-6">
                    <p class=" align-content-center">Available to:</p>
                    <div class="form-group col-sm-4">
                        @Html.TextBoxFor(x => x.AvailableTo, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
                        <p class="small">@Html.ValidationMessageFor(x => x.AvailableTo)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-7 mb-3 mb-sm-0">
                        @if (Model.TestCases != null && Model.TestCases.Count > 0)
                        {
                        <p class=" align-content-center">Current test cases:</p>
                            <table>
                                <tbody>
                                    <tr class="">
                                        <th>Name</th>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <th>Available to</th>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                    </tr>
                                @foreach (var testCase in Model.TestCases)
                                {
                                    <tr class="">
                                        <td border="1px" width="700" class="text-left">@testCase.Name</td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" class="text-center">@testCase.AvailableTo.ToShortDateString()</td>
                                        <td>&nbsp&nbsp&nbsp</td>
                                        <td border="1px" class="text-center">
                                            <a href="@Url.Action("DeleteAttachedTestCase", new {id = Model.Id, testCaseId = testCase.Id})" class="btn btn-primary btn-user btn-block">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-times"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                }

                                </tbody>
                            </table>
                        }
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-3 mb-3 mb-sm-0">
                        <p class="align-content-center mb-0">Test cases:</p>
                        <p class="align-content-center text-xs">(Available To must be equal or greater than availability of latest test case!)</p>
                        <input type="hidden" id="testCasesVal" name="data" />
                        <select class="mySelect2 form-control form-control-user"></select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2 mb-3 mb-sm-0">
                        <p class="align-content-center mb-0">Reward multiplier:</p>
                        <p class="align-content-center text-xs">(applied to each test case)</p>
                        <div class="input-group">
                            @Html.TextBoxFor(x => x.RewardMultiplier, new { @Value = (int)(Model.RewardMultiplier*100)-100, @class = "form-control form-control-user", @placeholder = "Enter value (0-100)", @type = "number", @min = "0", @max = "100", @step = "1", @id = "myPercent" })
                            <div class="input-group-append">
                                <div class="btn bg-primary text-white">
                                    <i class="fas fa-percentage"></i>
                                </div>
                            </div>
                        </div>
                        <p class="small">@Html.ValidationMessageFor(x => x.RewardMultiplier)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2 mb-3 mb-sm-0">
                        <a href="@Url.Action("CompanyTestGroups")" class="btn btn-primary btn-user btn-block">Back</a>
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary btn-user btn-block">Edit test group</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/select2.min.js")"></script>

<script>
    $(document).ready(function () {
        $('#myPercent').keypress(function (field) {
            field.preventDefault();
        });

        $(".mySelect2").select2({
            placeholder: "Select test cases",
            allowClear: true,
            multiple: true,
            ajax: {
                url: "@Url.Action("GetTestCases", "TestGroups")",
                datatype: 'json',
                delay: 250,
                multiple: true,
                data: function(params) {
                    return {
                        searchTerm: params.term
                    };
                },
                processResults: function(data, params) {
                    return {
                        results: data
                    };
                }
            }
        });

        $(".mySelect2").on("change",
            function() {
                var testCaseId = $(this).val();
                $("#testCasesVal").val(testCaseId);
            });
    });

</script>